# Site settings
title: Faysal Ishtiaq Rabby's CV 
description: Faysal Ishtiaq Rabby's CV
favicon: /assets/img/avatar.JPG
baseurl: https://faysal-ishtiaq.github.io/resumecard
url: https://faysal-ishtiaq.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: 

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Faysal Ishtiaq Rabby
  title: Student
  address: Khulna, Bangladesh
  email: f.i.rabby@gmail.com
  link: http://faysal-ishtiaq.github.io
  weibo:
  github: faysal-ishtiaq
  linkedin: firabby
  twitter: Faisal_Ishtiaq
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Systway
      location: Khulna, Bangladesh
      title: Web Developer
      started: 2014
      duration: (2014 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Lazy Few Apps
      location: Dhaka, Bangladesh
      title: Co-founder, Android Developer
      started: 2015
      duration: (October, 2015 - December, 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Bogra Cantonment Public School And Colege
      location: Bogra, Bangladesh
      degree: Secondary School Certificate
      major: Science
      started: 2004
      duration: (2004 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - education2:
      organization: Bogra Cantonment Public School And Colege
      location: Bogra, Bangladesh
      degree: Higher Secondary School Certificate
      major: Science
      started: 2009
      duration: (2009 - 20011)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Bengali
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 50%
    - skill5:
      name: Java/Java SE
      percentage: 50%
